#include <iostream>
using namespace std;
/**
Project Euler - Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

int main()
{
	const int N = 4000000;
	int a = 1;
	int b = 1;
	int s = 0;
	int n = 0;
	int p = 0;

while(p<=N)
{
	if(n == 0)
		{p = 1;}
	else if (n == 1)
		{ p=a+b;}
	else
	{
		a = b;
		b = p;
		p = a+b;
	}
	if((p % 2)==0)
		{
			s = s+p;
			cout << p<<"\n";
		}
		n++;
}
	cout<<"sum = " << s <<"\n";
}